### PR TITLE
Add riffle animation

### PR DESCRIPTION
**Pull request by mklewandowski**
This PR adds animated riffles to stream scenarios.  There are 2 unique riffle animations that can be added to scenarios A and B.

riffles

### CODE REVIEW

**Review by kswenson — APPROVED** [review]
👍 Looks good. I think there might be something I'm not getting about keys/indices, but in the interest of expediency we can come back to it later.

**Comment by mklewandowski** [comment]
> 👍 Looks good. I think there might be something I'm not getting about keys/indices, but in the interest of expediency we can come back to it later.

The extra info in the key string was to handle toggling between scenarios that both had riffles, but had different PNGs that were used by the animation component.  I wanted the animation type in the key string to guarantee the img element was unmounted. 
 Without the more detailed key string, there was an obvious flash that occurred when switching scenarios.

**Comment by mklewandowski** [comment]
@kswenson basically trying to protect against this:
flash

**Comment by kswenson** [comment]
>The extra info in the key string was to handle toggling between scenarios that both had riffles, but had different PNGs that were used by the animation component. I wanted the animation type in the key string to guarantee the img element was unmounted.
Without the more detailed key string, there was an obvious flash that occurred when switching scenarios.

I understand and support the use of unique keys. I'm more concerned about the other side of the coin -- indices are often a sign of poor keys, but we seem to be using both ids and indices in our keys even though I would think that the keys would be unique without indices at the animation level, but I may be missing something because of the haste of trying to get things in for the demo.

**Pull request merged**
